"""add pets and owners tables

Revision ID: 309371c58a5d
Revises: ed6af7dff1db
Create Date: 2023-04-18 23:47:55.213222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '309371c58a5d'
down_revision = 'ed6af7dff1db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'pet', 'owners', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pet', type_='foreignkey')
    op.drop_table('owners')
    # ### end Alembic commands ###
